sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - cp spec/config/auth/config.js src/auth/private/config.js
  - docker network create fyp-network
  - ./dist/neo4j.sh -t
  - ./dist/web.sh -t
  - ./dist/auth.sh -t
  - ./dist/api.sh -t
  - sleep 6m

script:
  - cd spec
  - npm install
  - npm test
