sudo: required

language: javascript

services: 
  - docker

before_install:
  - brctl addbr fyp-bridge
  - ip addr add 192.168.1.1 dev fyp-bridge
  - ip link set dev fyp-bridge up
  - echo 'DOCKER_OPTS="-b=fyp-bridge"' >> /etc/default/docker
  - docker network create fyp-network
  - docker pull neo4j:3.0
  - docker pull node:argon

script:
  - cd src/test
  - npm install
  - npm test
